In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

train = pd.read_csv('../data/train.csv')
test = pd.read_csv('../data/test.csv')

print(train.shape, test.shape)
train.info()

(891, 12) (418, 11)
<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [2]:
train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
train.shape
train.columns
train["Age"].mean()

np.float64(29.69911764705882)

In [4]:
train.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [5]:
train[train["Sex"] == "female"]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [6]:
train[train["Age"] < 10]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.00,3,1,349909,21.0750,NaN,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.00,1,1,PP 9549,16.7000,G6,S
16,17,0,3,"Rice, Master. Eugene",male,2.00,4,1,382652,29.1250,NaN,Q
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.00,3,1,349909,21.0750,NaN,S
43,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.00,1,2,SC/Paris 2123,41.5792,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
827,828,1,2,"Mallet, Master. Andre",male,1.00,0,2,S.C./PARIS 2079,37.0042,NaN,C
831,832,1,2,"Richards, Master. George Sibley",male,0.83,1,1,29106,18.7500,NaN,S
850,851,0,3,"Andersson, Master. Sigvard Harald Elias",male,4.00,4,2,347082,31.2750,NaN,S
852,853,0,3,"Boulos, Miss. Nourelain",female,9.00,1,1,2678,15.2458,NaN,C
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.00,1,1,347742,11.1333,NaN,S

In [7]:
train[(train["Sex"] == "female") & (train["Pclass"] == 1)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C
...,...,...,...,...,...,...,...,...,...,...,...,...
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.0,1,1,36928,164.8667,NaN,S
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S

In [8]:
train.groupby("Sex")["Survived"].mean()

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

In [9]:
train[(train["Pclass"] == 3)].shape

(491, 12)

In [10]:
train[(train["Age"] < 10)]["Survived"].mean()

np.float64(0.6129032258064516)

In [11]:
train.groupby("Pclass")["Survived"].mean()

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

In [12]:
from sklearn.impute import SimpleImputer

train = pd.read_csv("../data/train.csv")

imputer = SimpleImputer(strategy="median")
imputer.fit(train[["Age"]])
print(imputer.statistics_)

age_rempli = imputer.transform(train[["Age"]])
pd.DataFrame(age_rempli).isna().sum()

[28.]

0    0
dtype: int64

In [13]:
ImputEmbarked = SimpleImputer(strategy="most_frequent")
ImputEmbarked.fit(train[["Embarked"]])
print(ImputEmbarked.statistics_)
embarked_rempli = ImputEmbarked.transform(train[["Embarked"]])

['S']

In [14]:
imputer.transform(pd.read_csv("../data/test.csv")[["Age"]])

array([[34.5 ],
       [47.  ],
       [62.  ],
       [27.  ],
       [22.  ],
       [14.  ],
       [30.  ],
       [26.  ],
       [18.  ],
       [21.  ],
       [28.  ],
       [46.  ],
       [23.  ],
       [63.  ],
       [47.  ],
       [24.  ],
       [35.  ],
       [21.  ],
       [27.  ],
       [45.  ],
       [55.  ],
       [ 9.  ],
       [28.  ],
       [21.  ],
       [48.  ],
       [50.  ],
       [22.  ],
       [22.5 ],
       [41.  ],
       [28.  ],
       [50.  ],
       [24.  ],
       [33.  ],
       [28.  ],
       [30.  ],
       [18.5 ],
       [28.  ],
       [21.  ],
       [25.  ],
       [28.  ],
       [39.  ],
       [28.  ],
       [41.  ],
       [30.  ],
       [45.  ],
       [25.  ],
       [45.  ],
       [28.  ],
       [60.  ],
       [36.  ],
       [24.  ],
       [27.  ],
       [20.  ],
       [28.  ],
       [28.  ],
       [10.  ],
       [35.  ],
       [25.  ],
       [28.  ],
       [36.  ],
       [17.  ],
       [32.  ],
       [18.  ],
       [22.  ],
       [13.  ],
       [28.  ],
       [18.  ],
       [47.  ],
       [31.  ],
       [60.  ],
       [24.  ],
       [21.  ],
       [29.  ],
       [28.5 ],
       [35.  ],
       [32.5 ],
       [28.  ],
       [55.  ],
       [30.  ],
       [24.  ],
       [ 6.  ],
       [67.  ],
       [49.  ],
       [28.  ],
       [28.  ],
       [28.  ],
       [27.  ],
       [18.  ],
       [28.  ],
       [ 2.  ],
       [22.  ],
       [28.  ],
       [27.  ],
       [28.  ],
       [25.  ],
       [25.  ],
       [76.  ],
       [29.  ],
       [20.  ],
       [33.  ],
       [43.  ],
       [27.  ],
       [28.  ],
       [26.  ],
       [16.  ],
       [28.  ],
       [21.  ],
       [28.  ],
       [28.  ],
       [18.5 ],
       [41.  ],
       [28.  ],
       [36.  ],
       [18.5 ],
       [63.  ],
       [18.  ],
       [28.  ],
       [ 1.  ],
       [36.  ],
       [29.  ],
       [12.  ],
       [28.  ],
       [35.  ],
       [28.  ],
       [28.  ],
       [17.  ],
       [22.  ],
       [28.  ],
       [42.  ],
       [24.  ],
       [32.  ],
       [53.  ],
       [28.  ],
       [28.  ],
       [43.  ],
       [24.  ],
       [26.5 ],
       [26.  ],
       [23.  ],
       [40.  ],
       [10.  ],
       [33.  ],
       [61.  ],
       [28.  ],
       [42.  ],
       [31.  ],
       [28.  ],
       [22.  ],
       [28.  ],
       [30.  ],
       [23.  ],
       [28.  ],
       [60.5 ],
       [36.  ],
       [13.  ],
       [24.  ],
       [29.  ],
       [23.  ],
       [42.  ],
       [26.  ],
       [28.  ],
       [ 7.  ],
       [26.  ],
       [28.  ],
       [41.  ],
       [26.  ],
       [48.  ],
       [18.  ],
       [28.  ],
       [22.  ],
       [28.  ],
       [27.  ],
       [23.  ],
       [28.  ],
       [40.  ],
       [15.  ],
       [20.  ],
       [54.  ],
       [36.  ],
       [64.  ],
       [30.  ],
       [37.  ],
       [18.  ],
       [28.  ],
       [27.  ],
       [40.  ],
       [21.  ],
       [17.  ],
       [28.  ],
       [40.  ],
       [34.  ],
       [28.  ],
       [11.5 ],
       [61.  ],
       [ 8.  ],
       [33.  ],
       [ 6.  ],
       [18.  ],
       [23.  ],
       [28.  ],
       [28.  ],
       [ 0.33],
       [47.  ],
       [ 8.  ],
       [25.  ],
       [28.  ],
       [35.  ],
       [24.  ],
       [33.  ],
       [25.  ],
       [32.  ],
       [28.  ],
       [17.  ],
       [60.  ],
       [38.  ],
       [42.  ],
       [28.  ],
       [57.  ],
       [50.  ],
       [28.  ],
       [30.  ],
       [21.  ],
       [22.  ],
       [21.  ],
       [53.  ],
       [28.  ],
       [23.  ],
       [28.  ],
       [40.5 ],
       [36.  ],
       [14.  ],
       [21.  ],
       [21.  ],
       [28.  ],
       [39.  ],
       [20.  ],
       [64.  ],
       [20.  ],
       [18.  ],
       [48.  ],
       [55.  ],
       [45.  ],
       [45.  ],
       [28.  ],
       [28.  ],
       [41.  ],
       [22.  ],
       [42.  ],
       [29.  ],
       [28.  ],
       [ 0.92],
       [20.  ],
       [27.  ],
       [24.  ],
       [32.5 ],
       [28.  ],
       [28.  ],
       [28.  ],
       [19.  ],
       [21.  ],
       [36.5 ],
       [21.  ],
       [29.  ],
       [ 1.  ],
       [30.  ],
       [28.  ],
       [28.  ],
       [28.  ],
       [28.  ],
       [17.  ],
       [46.  ],
       [28.  ],
       [26.  ],
       [28.  ],
       [28.  ],
       [20.  ],
       [28.  ],
       [40.  ],
       [30.  ],
       [22.  ],
       [23.  ],
       [ 0.75],
       [28.  ],
       [ 9.  ],
       [ 2.  ],
       [36.  ],
       [28.  ],
       [24.  ],
       [28.  ],
       [28.  ],
       [28.  ],
       [30.  ],
       [28.  ],
       [53.  ],
       [36.  ],
       [26.  ],
       [ 1.  ],
       [28.  ],
       [30.  ],
       [29.  ],
       [32.  ],
       [28.  ],
       [43.  ],
       [24.  ],
       [28.  ],
       [64.  ],
       [30.  ],
       [ 0.83],
       [55.  ],
       [45.  ],
       [18.  ],
       [22.  ],
       [28.  ],
       [37.  ],
       [55.  ],
       [17.  ],
       [57.  ],
       [19.  ],
       [27.  ],
       [22.  ],
       [26.  ],
       [25.  ],
       [26.  ],
       [33.  ],
       [39.  ],
       [23.  ],
       [12.  ],
       [46.  ],
       [29.  ],
       [21.  ],
       [48.  ],
       [39.  ],
       [28.  ],
       [19.  ],
       [27.  ],
       [30.  ],
       [32.  ],
       [39.  ],
       [25.  ],
       [28.  ],
       [18.  ],
       [32.  ],
       [28.  ],
       [58.  ],
       [28.  ],
       [16.  ],
       [26.  ],
       [38.  ],
       [24.  ],
       [31.  ],
       [45.  ],
       [25.  ],
       [18.  ],
       [49.  ],
       [ 0.17],
       [50.  ],
       [59.  ],
       [28.  ],
       [28.  ],
       [30.  ],
       [14.5 ],
       [24.  ],
       [31.  ],
       [27.  ],
       [25.  ],
       [28.  ],
       [28.  ],
       [22.  ],
       [45.  ],
       [29.  ],
       [21.  ],
       [31.  ],
       [49.  ],
       [44.  ],
       [54.  ],
       [45.  ],
       [22.  ],
       [21.  ],
       [55.  ],
       [ 5.  ],
       [28.  ],
       [26.  ],
       [28.  ],
       [19.  ],
       [28.  ],
       [24.  ],
       [24.  ],
       [57.  ],
       [21.  ],
       [ 6.  ],
       [23.  ],
       [51.  ],
       [13.  ],
       [47.  ],
       [29.  ],
       [18.  ],
       [24.  ],
       [48.  ],
       [22.  ],
       [31.  ],
       [30.  ],
       [38.  ],
       [22.  ],
       [17.  ],
       [43.  ],
       [20.  ],
       [23.  ],
       [50.  ],
       [28.  ],
       [ 3.  ],
       [28.  ],
       [37.  ],
       [28.  ],
       [28.  ],
       [39.  ],
       [38.5 ],
       [28.  ],
       [28.  ]])

In [15]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(handle_unknown="ignore", sparse_output=False)
encoder.fit(train[["Sex"]])
print(encoder.categories_)

encoded = encoder.transform(train[["Sex"]])
print(encoded[:5])
print(train["Sex"].head())

[array(['female', 'male'], dtype=object)]
[[0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]]
0      male
1    female
2    female
3    female
4      male
Name: Sex, dtype: str

In [16]:
encodedEm = OneHotEncoder(handle_unknown="ignore", sparse_output=False)
encodedEm.fit(train[["Embarked"]])
print(encodedEm.categories_)

[array(['C', 'Q', 'S', nan], dtype=object)]

In [17]:
encodedEm.get_feature_names_out()
encodedEm.transform(pd.DataFrame({"Embarked": ["S", "C", "Q", "S"]}))

array([[0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

ICI on commence vrai code

In [18]:
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler

train = pd.read_csv("../data/train.csv")
test = pd.read_csv("../data/test.csv")

In [19]:
num_cols = ["Age", "Fare", "Pclass", "SibSp", "Parch"]
cat_cols = ["Sex", "Embarked"]

In [20]:
num_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

cat_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(drop="if_binary", handle_unknown="ignore", sparse_output=False)),
])

In [21]:
preprocess = ColumnTransformer([
    ("num", num_pipeline, num_cols),
    ("cat", cat_pipeline, cat_cols),
])

In [22]:
X_train = preprocess.fit_transform(train[num_cols + cat_cols])
X_test = preprocess.transform(test[num_cols + cat_cols])

print(X_train.shape, X_test.shape)
print(preprocess.get_feature_names_out())

(891, 9) (418, 9)
['num__Age' 'num__Fare' 'num__Pclass' 'num__SibSp' 'num__Parch'
 'cat__Sex_male' 'cat__Embarked_C' 'cat__Embarked_Q' 'cat__Embarked_S']

In [23]:
df_train = pd.DataFrame(X_train, columns=preprocess.get_feature_names_out())
df_train.head()

,num__Age,num__Fare,num__Pclass,num__SibSp,num__Parch,cat__Sex_male,cat__Embarked_C,cat__Embarked_Q,cat__Embarked_S
0,-0.565736,-0.502445,0.827377,0.432793,-0.473674,1.0,0.0,0.0,1.0
1,0.663861,0.786845,-1.566107,0.432793,-0.473674,0.0,1.0,0.0,0.0
2,-0.258337,-0.488854,0.827377,-0.474545,-0.473674,0.0,0.0,0.0,1.0
3,0.433312,0.420730,-1.566107,0.432793,-0.473674,0.0,0.0,0.0,1.0
4,0.433312,-0.486337,0.827377,-0.474545,-0.473674,1.0,0.0,0.0,1.0

In [24]:
print(df_train["num__Age"].mean())
df_train["num__Age"].head()

2.272779794518839e-16

0   -0.565736
1    0.663861
2   -0.258337
3    0.433312
4    0.433312
Name: num__Age, dtype: float64

In [25]:
X = train[num_cols + cat_cols]
y = train["Survived"]

from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier

model = Pipeline([
    ("prep", preprocess),
    ("clf", XGBClassifier(n_estimators=300, learning_rate=0.05, max_depth=3, random_state=42)),])

In [26]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(model, X, y, cv=5, scoring="accuracy")
print(scores)
print(f"{scores.mean():.3f} ± {scores.std():.3f}")

[0.81564246 0.81460674 0.85393258 0.80898876 0.83707865]
0.826 ± 0.017

In [27]:
model.fit(X, y)
predictions = model.predict(test[num_cols + cat_cols])

In [28]:
submission = pd.DataFrame({
    "PassengerId": test["PassengerId"],
    "Survived": predictions,
})
submission.to_csv("submission.csv", index=False)
print(submission.shape)
submission.head(15)

(418, 2)

    PassengerId  Survived
0           892         0
1           893         0
2           894         0
3           895         0
4           896         0
5           897         0
6           898         1
7           899         0
8           900         1
9           901         0
10          902         0
11          903         0
12          904         1
13          905         0
14          906         1

In [29]:
def add_features(df):
    df = df.copy()
    df["Title"] = df["Name"].str.extract(r" ([A-Za-z]+)\.", expand=False)
    df["Title"] = df["Title"].replace(
        ["Mlle", "Ms"], "Miss").replace("Mme", "Mrs")
    rares = ["Dr", "Rev", "Col", "Major", "Capt", "Sir", "Lady",
             "Countess", "Don", "Dona", "Jonkheer"]
    df["Title"] = df["Title"].replace(rares, "Rare")
    df["FamilySize"] = df["SibSp"] + df["Parch"] + 1
    df["IsAlone"] = (df["FamilySize"] == 1).astype(int)
    return df

train2 = add_features(train)
test2 = add_features(test)

In [30]:
num_cols = ["Age", "Fare", "Pclass", "SibSp", "Parch", "FamilySize", "IsAlone"]
cat_cols = ["Sex", "Embarked", "Title"]

preprocess = ColumnTransformer([
    ("num", num_pipeline, num_cols),
    ("cat", cat_pipeline, cat_cols),
])

model = Pipeline([
    ("prep", preprocess),
    ("clf", XGBClassifier(n_estimators=300, learning_rate=0.05,
                          max_depth=3, random_state=42)),
])

X2 = train2[num_cols + cat_cols]
y = train2["Survived"]

scores = cross_val_score(model, X2, y, cv=5, scoring="accuracy")
print(f"{scores.mean():.3f} ± {scores.std():.3f}")

0.836 ± 0.019

In [31]:
model.fit(X2, y)
predictions = model.predict(test2[num_cols + cat_cols])

submission2 = pd.DataFrame({
    "PassengerId": test2["PassengerId"],
    "Survived": predictions,
})
submission2.to_csv("submission2.csv", index=False)
print(submission2.shape)
submission2.head(15)

(418, 2)

    PassengerId  Survived
0           892         0
1           893         0
2           894         0
3           895         0
4           896         1
5           897         0
6           898         0
7           899         0
8           900         1
9           901         0
10          902         0
11          903         0
12          904         1
13          905         0
14          906         1